apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-go-gh 
  description: Secure Supply Chain Example for Go Runtime http based application with advanced continuous integration pipeline covering building, CVE scanning, security scanning, signatures,  attestations, SLSA provenance and SBOM along with Gitops-based continuous deployment   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:
    # ArgoCD apps from this template used rhtap-gitops as the grouping
    argocd/app-selector: rhtap/gitops=azure-go-gh
    backstage.io/kubernetes-id: azure-go-gh 
    backstage.io/techdocs-ref: dir:.
    # dev.azure.com/project-repo: lucarval-rhtap/azure-go-gh
    dev.azure.com/project: shared-public
    dev.azure.com/build-definition: lucarval-rhtap.azure-go-gh
    quay.io/repository-slug: lucarval-rhtap/azure-go-gh
  tags: ["go", "sscs", "sbom", "acs"] 
spec:
  type: service
  owner: group:default/lcarva 
  lifecycle: experimental
 
