apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: azure-go-gh
  janus-idp.io/tekton: azure-go-gh
  backstage.io/kubernetes-id: azure-go-gh
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: azure-go-gh
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
